Name:                language-javascript
Version:             0.8.0.0
Synopsis:            Parser for JavaScript
Description:         Parses Javascript into an Abstract Syntax Tree (AST).  Initially intended as frontend to hjsmin.
                     .
                     Note: Version 0.5.0 breaks compatibility with prior versions, the AST has been reworked to allow
                     round trip processing of JavaScript.
License:             BSD3
License-file:        LICENSE
Author:              Alan Zimmerman
Maintainer:          Erik de Castro Lopo <erikd@mega-nerd.com>
Copyright:           (c) 2010-2015 Alan Zimmerman
                     (c) 2015-2019 Erik de Castro Lopo
                     (c) 2018      Daniel Gasienica
Category:            Language
Build-type:          Simple
homepage:            https://github.com/erikd/language-javascript
bug-reports:         https://github.com/erikd/language-javascript/issues
Extra-source-files:  README.md
                     ChangeLog.md
                     .ghci
                     test/Unicode.js
                     test/fixtures/k.js
                     test/fixtures/unicode.txt
                     -- Note: Removed Lexer.x as we now use flatparse for lexing

-- Version requirement upped for test support in later Cabal
Cabal-version:   >= 1.9.2

Tested-with:     GHC == 9.2.8, GHC == 9.4.8, GHC == 9.6.4, GHC == 9.8.2

Library
  default-language:    Haskell2010
  Build-depends:     base             >= 4       && < 5
                   , mtl              >= 1.1     && < 2.4
                   , containers       >= 0.2     && < 0.8
                   , blaze-builder    >= 0.2     && < 0.5
                   , bytestring       >= 0.9.1   && < 0.13
                   , text             >= 1.2     && < 2.2
                   , utf8-string      >= 0.3.7   && < 2
                   , deepseq          >= 1.3     && < 1.6
                   , microlens        >= 0.4     && < 0.5
                   , microlens-th     >= 0.4     && < 0.5
                   , flatparse        >= 0.5.1   && < 0.6
                   , vector           >= 0.12    && < 0.14
                   , template-haskell >= 2.16    && < 2.22
                   , haskell-src-meta >= 0.8     && < 0.9
  if !impl(ghc>=8.0)
    build-depends:   semigroups       >= 0.16.1

  hs-source-dirs: src
  Exposed-modules:     Language.JavaScript.Parser
                       Language.JavaScript.Parser.AST
                       Language.JavaScript.Parser.Parser
                       Language.JavaScript.Parser.ParseError
                       Language.JavaScript.Parser.SrcLocation
                       Language.JavaScript.Parser.Token
                       Language.JavaScript.Parser.Build
                       Language.JavaScript.Parser.Validator
                       Language.JavaScript.QQ
                       Language.JavaScript.QQ.Validate
                       Language.JavaScript.QQ.Compile
                       Language.JavaScript.QQ.Antiquote
                       Language.JavaScript.Pretty.Printer
                       Language.JavaScript.Pretty.JSON
                       Language.JavaScript.Pretty.XML
                       Language.JavaScript.Pretty.SExpr
                       Language.JavaScript.Process.Minify
                       Language.JavaScript.Process.TreeShake
                       Language.JavaScript.Process.TreeShake.Types
                       Language.JavaScript.Parser.Core
                       Language.JavaScript.Parser.Grammar
  Other-modules:       Language.JavaScript.Process.TreeShake.Analysis
                     , Language.JavaScript.Process.TreeShake.Elimination
                     , Language.JavaScript.Parser.Pos
                     , Language.JavaScript.Parser.Primitives
                     , Language.JavaScript.Parser.Lexer
                     , Language.JavaScript.Parser.Operators
                     , Language.JavaScript.Parser.Literals
                     , Language.JavaScript.Parser.CommentScanner
  ghc-options:         -Wall -fwarn-tabs -O1 -funbox-strict-fields -fspec-constr-count=6 -fno-state-hack

Test-Suite testsuite
  Type: exitcode-stdio-1.0
  default-language:    Haskell2010
  Main-is: testsuite.hs
  hs-source-dirs: test
  other-modules:
    Test.Language.Javascript.JSDocTest
  ghc-options:   -Wall -fwarn-tabs
  build-depends: base             >= 4       && < 5
                 , Cabal           >= 1.9.2   && < 3.12
                 , QuickCheck      >= 2       && < 2.16
                 , hspec           >= 2.7     && < 2.12
                 , hspec-golden    >= 0.2     && < 0.3
                 , criterion       >= 1.1     && < 1.7
                 , weigh           >= 0.0.10  && < 0.1
                 , temporary       >= 1.2     && < 1.4
                 , filepath        >= 1.3     && < 1.6
                 , directory       >= 1.2     && < 1.4
                 , containers      >= 0.2     && < 0.8
                 , mtl             >= 1.1     && < 2.4
                 , text            >= 1.2     && < 2.2
                 , utf8-string     >= 0.3.7   && < 2
                 , bytestring      >= 0.9.1   && < 0.13
                 , blaze-builder   >= 0.2     && < 0.5
                 , deepseq         >= 1.3     && < 1.6
                 , time            >= 1.4     && < 1.15
                 , process         >= 1.2     && < 1.7
                 , random          >= 1.1     && < 1.3
                 , aeson           >= 1.0     && < 2.3
                 , microlens       >= 0.4     && < 0.5
                 , flatparse       >= 0.5.1   && < 0.6
                 , vector          >= 0.12    && < 0.14
                 , language-javascript

  Other-modules:
                    -- Unit Tests - Lexer
                    Unit.Language.Javascript.Parser.Lexer.BasicLexer
                    Unit.Language.Javascript.Parser.Lexer.AdvancedLexer
                    Unit.Language.Javascript.Parser.Lexer.ASIHandling
                    Unit.Language.Javascript.Parser.Lexer.NumericLiterals
                    Unit.Language.Javascript.Parser.Lexer.StringLiterals
                    Unit.Language.Javascript.Parser.Lexer.UnicodeSupport

                    -- Unit Tests - Parser
                    Unit.Language.Javascript.Parser.Parser.Expressions
                    Unit.Language.Javascript.Parser.Parser.Statements
                    Unit.Language.Javascript.Parser.Parser.Programs
                    Unit.Language.Javascript.Parser.Parser.Modules
                    Unit.Language.Javascript.Parser.Parser.ExportStar
                    Unit.Language.Javascript.Parser.Parser.Literals

                    -- Unit Tests - Flatparse
                    Unit.Language.Javascript.Parser.Flatparse.StatementTest

                    -- Unit Tests - AST
                    Unit.Language.Javascript.Parser.AST.Construction
                    Unit.Language.Javascript.Parser.AST.Generic
                    Unit.Language.Javascript.Parser.AST.SrcLocation

                    -- Unit Tests - JSDoc
                    -- Test.Language.Javascript.JSDocTest  -- Temporarily disabled

                    -- Unit Tests - Pretty Printing
                    Unit.Language.Javascript.Parser.Pretty.JSONTest
                    Unit.Language.Javascript.Parser.Pretty.XMLTest
                    Unit.Language.Javascript.Parser.Pretty.SExprTest

                    -- Unit Tests - Validation
                    Unit.Language.Javascript.Parser.Validation.Core
                    Unit.Language.Javascript.Parser.Validation.ES6Features
                    Unit.Language.Javascript.Parser.Validation.StrictMode
                    Unit.Language.Javascript.Parser.Validation.Modules
                    Unit.Language.Javascript.Parser.Validation.ControlFlow

                    -- Unit Tests - Runtime Validation
                    Unit.Language.Javascript.Runtime.ValidatorTest

                    -- Unit Tests - Quasi-Quoters
                    Unit.Language.Javascript.Parser.QQ.Validate
                    Unit.Language.Javascript.Parser.QQ.Compile
                    Unit.Language.Javascript.Parser.QQ.Antiquote

                    -- Unit Tests - Error
                    Unit.Language.Javascript.Parser.Error.Recovery
                    Unit.Language.Javascript.Parser.Error.AdvancedRecovery
                    Unit.Language.Javascript.Parser.Error.Quality
                    Unit.Language.Javascript.Parser.Error.Negative

                    -- Unit Tests - TreeShake
                    Unit.Language.Javascript.Process.TreeShake.Core
                    Unit.Language.Javascript.Process.TreeShake.Advanced
                    Unit.Language.Javascript.Process.TreeShake.Stress
                    Unit.Language.Javascript.Process.TreeShake.FrameworkPatterns
                    Unit.Language.Javascript.Process.TreeShake.AdvancedJSEdgeCases
                    Unit.Language.Javascript.Process.TreeShake.LibraryPatterns
                    Unit.Language.Javascript.Process.TreeShake.IntegrationScenarios
                    Unit.Language.Javascript.Process.TreeShake.EnterpriseScale

                    -- Integration Tests
                    Integration.Language.Javascript.Parser.RoundTrip
                    -- Integration.Language.Javascript.Parser.AdvancedFeatures  -- Temporarily disabled
                    Integration.Language.Javascript.Parser.Minification
                    Integration.Language.Javascript.Process.TreeShake

                    -- Golden Tests
                    Golden.Language.Javascript.Parser.GoldenTests

                    -- Property Tests
                    Properties.Language.Javascript.Parser.CoreProperties
                    Properties.Language.Javascript.Parser.Generators
                    Properties.Language.Javascript.Parser.GeneratorsTest
                    Properties.Language.Javascript.Parser.Fuzzing

                    -- Fuzz Tests
                    Properties.Language.Javascript.Parser.Fuzz.CoverageGuided
                    Properties.Language.Javascript.Parser.Fuzz.DifferentialTesting
                    Properties.Language.Javascript.Parser.Fuzz.FuzzGenerators
                    Properties.Language.Javascript.Parser.Fuzz.FuzzHarness
                    Properties.Language.Javascript.Parser.Fuzz.FuzzTest

                    -- Benchmark Tests
                    Benchmarks.Language.Javascript.Parser.Performance
                    Benchmarks.Language.Javascript.Parser.Memory
                    Benchmarks.Language.Javascript.Parser.ErrorRecovery


Benchmark parser-bench
  Type: exitcode-stdio-1.0
  default-language:    Haskell2010
  Main-is: Main.hs
  hs-source-dirs: bench
  ghc-options:   -Wall -O2 -rtsopts
  build-depends: base             >= 4       && < 5
                 , bytestring      >= 0.9.1   && < 0.13
                 , criterion       >= 1.1     && < 1.7
                 , deepseq         >= 1.3     && < 1.6
                 , language-javascript

source-repository head
  type:     git
  location: https://github.com/erikd/language-javascript.git
