Name:                language-javascript
Version:             0.7.1.0
Synopsis:            Parser for JavaScript
Description:         Parses Javascript into an Abstract Syntax Tree (AST).  Initially intended as frontend to hjsmin.
                     .
                     Note: Version 0.5.0 breaks compatibility with prior versions, the AST has been reworked to allow
                     round trip processing of JavaScript.
License:             BSD3
License-file:        LICENSE
Author:              Alan Zimmerman
Maintainer:          Erik de Castro Lopo <erikd@mega-nerd.com>
Copyright:           (c) 2010-2015 Alan Zimmerman
                     (c) 2015-2019 Erik de Castro Lopo
                     (c) 2018      Daniel Gasienica
Category:            Language
Build-type:          Simple
homepage:            https://github.com/erikd/language-javascript
bug-reports:         https://github.com/erikd/language-javascript/issues
Extra-source-files:  README.md
                     ChangeLog.md
                     .ghci
                     test/Unicode.js
                     test/k.js
                     test/unicode.txt
                     src/Language/JavaScript/Parser/Lexer.x

-- Version requirement upped for test support in later Cabal
Cabal-version:   >= 1.9.2


Library
  default-language:    Haskell2010
  Build-depends:     base             >= 4       && < 5
                   , array            >= 0.3
                   , mtl              >= 1.1
                   , containers       >= 0.2
                   , blaze-builder    >= 0.2
                   , bytestring       >= 0.9.1
                   , text             >= 1.2
                   , utf8-string      >= 0.3.7 && < 2
                   , deepseq          >= 1.3
                   , hashtables       >= 1.2
  if !impl(ghc>=8.0)
    build-depends:   semigroups       >= 0.16.1

  if impl(ghc >= 7.10)
    build-tools:       happy >= 1.19, alex >= 3.1.4
  else
    if impl(ghc >= 7.8)
      build-tools:       happy >= 1.19, alex >= 3.1
    else
      build-tools:       happy >= 1.18.5, alex >= 3.0.5
  hs-source-dirs: src
  Exposed-modules:     Language.JavaScript.Parser
                       Language.JavaScript.Parser.AST
                       Language.JavaScript.Parser.Grammar7
                       Language.JavaScript.Parser.Lexer
                       Language.JavaScript.Parser.Parser
                       Language.JavaScript.Parser.ParseError
                       Language.JavaScript.Parser.SrcLocation
                       Language.JavaScript.Parser.Token
                       Language.JavaScript.Parser.Validator
                       Language.JavaScript.Pretty.Printer
                       Language.JavaScript.Pretty.JSON
                       Language.JavaScript.Pretty.XML
                       Language.JavaScript.Pretty.SExpr
                       Language.JavaScript.Process.Minify
  Other-modules:       Language.JavaScript.Parser.LexerUtils
                       Language.JavaScript.Parser.ParserMonad
  ghc-options:         -Wall -fwarn-tabs -O2 -funbox-strict-fields -fspec-constr-count=6 -fno-state-hack

Test-Suite testsuite
  Type: exitcode-stdio-1.0
  default-language:    Haskell2010
  Main-is: testsuite.hs
  hs-source-dirs: test
  ghc-options:   -Wall -fwarn-tabs
  build-depends: base, Cabal >= 1.9.2
                 , QuickCheck >= 2
                 , hspec
                 , hspec-golden     >= 0.2
                 , criterion        >= 1.1
                 , weigh            >= 0.0.10
                 , temporary        >= 1.2
                 , filepath         >= 1.3
                 , directory        >= 1.2
                 , array            >= 0.3
                 , containers       >= 0.2
                 , mtl              >= 1.1
                 , text             >= 1.2
                 , utf8-string      >= 0.3.7 && < 2
                 , bytestring       >= 0.9.1
                 , blaze-builder    >= 0.2
                 , deepseq          >= 1.3
                 , time             >= 1.4
                 , process          >= 1.2
                 , random           >= 1.1
                 , aeson            >= 1.0
                 , language-javascript

  Other-modules:
                    -- Unit Tests - Lexer
                    Unit.Language.Javascript.Parser.Lexer.BasicLexer
                    Unit.Language.Javascript.Parser.Lexer.AdvancedLexer
                    Unit.Language.Javascript.Parser.Lexer.ASIHandling
                    Unit.Language.Javascript.Parser.Lexer.NumericLiterals
                    Unit.Language.Javascript.Parser.Lexer.StringLiterals
                    Unit.Language.Javascript.Parser.Lexer.UnicodeSupport
                    
                    -- Unit Tests - Parser
                    Unit.Language.Javascript.Parser.Parser.Expressions
                    Unit.Language.Javascript.Parser.Parser.Statements
                    Unit.Language.Javascript.Parser.Parser.Programs
                    Unit.Language.Javascript.Parser.Parser.Modules
                    Unit.Language.Javascript.Parser.Parser.ExportStar
                    Unit.Language.Javascript.Parser.Parser.Literals
                    
                    -- Unit Tests - AST
                    Unit.Language.Javascript.Parser.AST.Construction
                    Unit.Language.Javascript.Parser.AST.Generic
                    Unit.Language.Javascript.Parser.AST.SrcLocation
                    
                    -- Unit Tests - Pretty Printing
                    Unit.Language.Javascript.Parser.Pretty.JSONTest
                    Unit.Language.Javascript.Parser.Pretty.XMLTest
                    Unit.Language.Javascript.Parser.Pretty.SExprTest
                    
                    -- Unit Tests - Validation
                    Unit.Language.Javascript.Parser.Validation.Core
                    Unit.Language.Javascript.Parser.Validation.ES6Features
                    Unit.Language.Javascript.Parser.Validation.StrictMode
                    Unit.Language.Javascript.Parser.Validation.Modules
                    Unit.Language.Javascript.Parser.Validation.ControlFlow
                    
                    -- Unit Tests - Error
                    Unit.Language.Javascript.Parser.Error.Recovery
                    Unit.Language.Javascript.Parser.Error.AdvancedRecovery
                    Unit.Language.Javascript.Parser.Error.Quality
                    Unit.Language.Javascript.Parser.Error.Negative
                    
                    -- Integration Tests
                    Integration.Language.Javascript.Parser.RoundTrip
                    -- Integration.Language.Javascript.Parser.AdvancedFeatures  -- Temporarily disabled
                    Integration.Language.Javascript.Parser.Minification
                    Integration.Language.Javascript.Parser.Compatibility
                    
                    -- Golden Tests
                    Golden.Language.Javascript.Parser.GoldenTests
                    
                    -- Property Tests
                    Properties.Language.Javascript.Parser.CoreProperties
                    Properties.Language.Javascript.Parser.Generators
                    Properties.Language.Javascript.Parser.GeneratorsTest
                    Properties.Language.Javascript.Parser.Fuzzing
                    
                    -- Fuzz Tests
                    Properties.Language.Javascript.Parser.Fuzz.CoverageGuided
                    Properties.Language.Javascript.Parser.Fuzz.DifferentialTesting
                    Properties.Language.Javascript.Parser.Fuzz.FuzzGenerators
                    Properties.Language.Javascript.Parser.Fuzz.FuzzHarness
                    Properties.Language.Javascript.Parser.Fuzz.FuzzTest
                    
                    -- Benchmark Tests
                    Benchmarks.Language.Javascript.Parser.Performance
                    Benchmarks.Language.Javascript.Parser.Memory
                    Benchmarks.Language.Javascript.Parser.ErrorRecovery

-- Coverage-driven test generation tool
Executable coverage-gen
  Main-is: Main.hs
  default-language:    Haskell2010
  hs-source-dirs: tools/coverage-gen
  ghc-options: -Wall -fwarn-tabs -threaded -rtsopts -with-rtsopts=-N
  build-depends: base >= 4 && < 5
               , text >= 1.2
               , containers >= 0.2
               , vector >= 0.11
               , random >= 1.1
               , MonadRandom >= 0.5
               , process >= 1.2
               , directory >= 1.2
               , filepath >= 1.3
               , time >= 1.4
               , language-javascript
  Other-modules: Coverage.Analysis
               , Coverage.Generation
               , Coverage.Optimization
               , Coverage.Corpus
               , Coverage.Integration

 

source-repository head
  type:     git
  location: https://github.com/erikd/language-javascript.git
